version: '3.7'

services:

  pricetrakt-app:
    image: pricetrakt/pricetrakt
    container_name: pricetrakt
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - app.env
    networks:
      pricetrakt_network:

networks:
  pricetrakt_network:
    external: false